<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BookSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('books')->insert([
            [
                'name' => 'Đại số 10',
                'category_id' => 3,
                'publisher_id' => 3,
                'supplier_id' => 3,
                'size' => null,
                'weight' => null,
                'num_pages' => null,
                'language' => null,
                'price' => 20000,
                'e_book_price' => null,
                'quantity' => 50,
                'slug' => 'dai-so-10',
            ],
            [
                'name' => 'Hình học 10',
                'category_id' => 3,
                'publisher_id' => 3,
                'supplier_id' => 3,
                'size' => null,
                'weight' => null,
                'num_pages' => null,
                'language' => null,
                'price' => 20000,
                'e_book_price' => null,
                'quantity' => 50,
                'slug' => 'hinh-hoc-10',
            ],
            [
                'name' => 'Ngữ văn 10',
                'category_id' => 3,
                'publisher_id' => 3,
                'supplier_id' => 3,
                'size' => null,
                'weight' => null,
                'num_pages' => null,
                'language' => null,
                'price' => 20000,
                'e_book_price' => null,
                'quantity' => 50,
                'slug' => 'ngu-van-10',
            ],
            [
                'name' => 'Tiếng anh 10',
                'category_id' => 3,
                'publisher_id' => 3,
                'supplier_id' => 3,
                'size' => null,
                'weight' => null,
                'num_pages' => null,
                'language' => null,
                'price' => 20000,
                'e_book_price' => null,
                'quantity' => 50,
                'slug' => 'tieng-anh-10',
            ],
            [
                'name' => 'Vật lí 10',
                'category_id' => 3,
                'publisher_id' => 3,
                'supplier_id' => 3,
                'size' => null,
                'weight' => null,
                'num_pages' => null,
                'language' => null,
                'price' => 20000,
                'e_book_price' => null,
                'quantity' => 50,
                'slug' => 'vat-li-10',
            ],
            [
                'name' => 'Hoá học 10',
                'category_id' => 3,
                'publisher_id' => 3,
                'supplier_id' => 3,
                'size' => null,
                'weight' => null,
                'num_pages' => null,
                'language' => null,
                'price' => 20000,
                'e_book_price' => null,
                'quantity' => 50,
                'slug' => 'hoa-hoc-10',
            ],
            [
                'name' => 'Bứt phá điểm thi THPT quốc gia môn Toán',
                'category_id' => 3,
                'publisher_id' => 2,
                'supplier_id' => 2,
                'size' => null,
                'weight' => null,
                'num_pages' => null,
                'language' => null,
                'price' => 50000,
                'e_book_price' => null,
                'quantity' => 50,
                'slug' => 'but-pha-diem-thi-thpt-quoc-gia-mon-toan',
            ],
            [
                'name' => 'Bứt phá điểm thi THPT quốc gia môn Ngữ văn',
                'category_id' => 3,
                'publisher_id' => 2,
                'supplier_id' => 2,
                'size' => null,
                'weight' => null,
                'num_pages' => null,
                'language' => null,
                'price' => 50000,
                'e_book_price' => null,
                'quantity' => 50,
                'slug' => 'but-pha-diem-thi-thpt-quoc-gia-mon-ngu-van',
            ],
            [
                'name' => 'Bứt phá điểm thi THPT quốc gia môn Tiếng anh',
                'category_id' => 3,
                'publisher_id' => 2,
                'supplier_id' => 2,
                'size' => null,
                'weight' => null,
                'num_pages' => null,
                'language' => null,
                'price' => 50000,
                'e_book_price' => null,
                'quantity' => 50,
                'slug' => 'but-pha-diem-thi-thpt-quoc-gia-mon-tieng-anh',
            ],
            [
                'name' => 'Chú thuật hồi chiến 1',
                'category_id' => 2,
                'publisher_id' => 1,
                'supplier_id' => 1,
                'size' => null,
                'weight' => null,
                'num_pages' => null,
                'language' => null,
                'price' => 30000,
                'e_book_price' => null,
                'quantity' => 30,
                'slug' => 'chu-thuat-hoi-chien-1',
            ],
            [
                'name' => 'Chú thuật hồi chiến 2',
                'category_id' => 2,
                'publisher_id' => 1,
                'supplier_id' => 1,
                'size' => null,
                'weight' => null,
                'num_pages' => null,
                'language' => null,
                'price' => 30000,
                'e_book_price' => null,
                'quantity' => 30,
                'slug' => 'chu-thuat-hoi-chien-2',
            ],
            [
                'name' => 'Chú thuật hồi chiến 3',
                'category_id' => 2,
                'publisher_id' => 1,
                'supplier_id' => 1,
                'size' => null,
                'weight' => null,
                'num_pages' => null,
                'language' => null,
                'price' => 30000,
                'e_book_price' => null,
                'quantity' => 30,
                'slug' => 'chu-thuat-hoi-chien-3',
            ],
            [
                'name' => 'Chú thuật hồi chiến 4',
                'category_id' => 2,
                'publisher_id' => 1,
                'supplier_id' => 1,
                'size' => null,
                'weight' => null,
                'num_pages' => null,
                'language' => null,
                'price' => 30000,
                'e_book_price' => null,
                'quantity' => 30,
                'slug' => 'chu-thuat-hoi-chien-4',
            ],
            [
                'name' => 'Thám tử lừng danh Conan 100',
                'category_id' => 2,
                'publisher_id' => 1,
                'supplier_id' => 1,
                'size' => null,
                'weight' => null,
                'num_pages' => null,
                'language' => null,
                'price' => 20000,
                'e_book_price' => null,
                'quantity' => 25,
                'slug' => 'tham-tu-lung-danh-conan-100',
            ],
            [
                'name' => 'Chainsaw man 1',
                'category_id' => 2,
                'publisher_id' => 2,
                'supplier_id' => 2,
                'size' => null,
                'weight' => null,
                'num_pages' => null,
                'language' => null,
                'price' => 45000,
                'e_book_price' => null,
                'quantity' => 40,
                'slug' => 'chainsaw-man-1',
            ],
            [
                'name' => 'Đắc nhân tâm',
                'category_id' => 1,
                'publisher_id' => 2,
                'supplier_id' => 2,
                'size' => '20.5 x 14.5 cm x 1.9',
                'weight' => 350,
                'num_pages' => 320,
                'language' => 'Tiếng việt',
                'price' => 86000,
                'e_book_price' => 50000,
                'quantity' => 50,
                'slug' => 'dac-nhan-tam',
            ],
            [
                'name' => 'Quẳng gánh lo đi và vui sống',
                'category_id' => 1,
                'publisher_id' => 2,
                'supplier_id' => 2,
                'size' => '20.5 x 14.5 cm x 1.9',
                'weight' => 350,
                'num_pages' => 320,
                'language' => 'Tiếng việt',
                'price' => 75000,
                'e_book_price' => 50000,
                'quantity' => 50,
                'slug' => 'quang-ganh-lo-di-va-vui-song',
            ],
            [
                'name' => 'Tuổi trẻ đáng giá bao nhiêu?',
                'category_id' => 1,
                'publisher_id' => 2,
                'supplier_id' => 2,
                'size' => '20.5 x 14.5 cm x 1.9',
                'weight' => 350,
                'num_pages' => 320,
                'language' => 'Tiếng việt',
                'price' => 75000,
                'e_book_price' => 50000,
                'quantity' => 50,
                'slug' => 'tuoi-tre-dang-gia-bao-nhieu',
            ],
            [
                'name' => 'Mình nói gì khi nói về hạnh phúc?',
                'category_id' => 1,
                'publisher_id' => 2,
                'supplier_id' => 2,
                'size' => '20.5 x 14.5 cm x 1.9',
                'weight' => 350,
                'num_pages' => 320,
                'language' => 'Tiếng việt',
                'price' => 75000,
                'e_book_price' => 50000,
                'quantity' => 50,
                'slug' => 'minh-noi-gi-khi-noi-ve-hanh-phuc',
            ],
            [
                'name' => 'Cho tôi xin một vé đi tuổi thơ',
                'category_id' => 1,
                'publisher_id' => 2,
                'supplier_id' => 2,
                'size' => '20.5 x 14.5 cm x 1.9',
                'weight' => 350,
                'num_pages' => 320,
                'language' => 'Tiếng việt',
                'price' => 75000,
                'e_book_price' => 50000,
                'quantity' => 50,
                'slug' => 'cho-toi-xin-mot-ve-di-tuoi-tho',
            ],
            [
                'name' => 'Cà phê cùng Tony',
                'category_id' => 1,
                'publisher_id' => 2,
                'supplier_id' => 2,
                'size' => '20.5 x 14.5 cm x 1.9',
                'weight' => 350,
                'num_pages' => 320,
                'language' => 'Tiếng việt',
                'price' => 75000,
                'e_book_price' => 50000,
                'quantity' => 50,
                'slug' => 'ca-phe-cung-tony',
            ],
        ]);
    }
}
